// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleCabDataETLProject.DAL.Persistence;

#nullable disable

namespace SampleCabDataETLProject.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250315121557_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SampleCabDataETLProject.DAL.Entities.SampleCabDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<int>("PULocationID")
                        .HasColumnType("int");

                    b.Property<double>("fare_amount")
                        .HasColumnType("float");

                    b.Property<int>("passenger_count")
                        .HasColumnType("int");

                    b.Property<string>("store_and_fwd_flag")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<double>("tip_amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("tpep_dropoff_datetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tpep_pickup_datetime")
                        .HasColumnType("datetime2");

                    b.Property<double>("trip_distance")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CabDataEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
